doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

#        mapping_types:
#            training_status_enum: string
#            day_of_week_enum: string
#            membership_status_enum: string
#            payment_category_enum: string
#            payment_status_enum: string
#        types:
#            training_status_enum: 'App/Enum/BookingStatusEnum'
#            day_of_week_enum: 'App/Enum/DayOfWeekEnum'
#            membership_status_enum: 'App/Enum/MembershipStatusEnum'
#            payment_category_enum: 'App/Enum/PaymentCategoryEnum'
#            payment_status_enum: 'App/Enum/PaymentStatusEnum'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
#            App:
#                type: attribute
#                is_bundle: false
#                dir: '%kernel.project_dir%/src/Entity'
#                prefix: 'App\Entity'
#                alias: App
            Client:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Client/Entity'
                prefix: 'App\Client\Entity'
                alias: Client
            Booking:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Booking/Entity'
                prefix: 'App\Booking\Entity'
                alias: Booking
            Membership:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Membership/Entity'
                prefix: 'App\Membership\Entity'
                alias: Client
            Payment:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Payment/Entity'
                prefix: 'App\Payment\Entity'
                alias: Payment
            TrainingType:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/TrainingType/Entity'
                prefix: 'App\TrainingType\Entity'
                alias: TrainingType
            Trainer:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Trainer/Entity'
                prefix: 'App\Trainer\Entity'
                alias: Trainer
            TrainerAvailability:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/TrainerAvailability/Entity'
                prefix: 'App\TrainerAvailability\Entity'
                alias: TrainerAvailability
            Training:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Training/Entity'
                prefix: 'App\Training\Entity'
                alias: Training
            MembershipPlan:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/MembershipPlan/Entity'
                prefix: 'App\MembershipPlan\Entity'
                alias: MembershipPlan
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
